// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title Risk Oracle Interface
/// @notice Interface for storing and retrieving DeFi risk assessments
interface IRiskOracle {

    /// @notice Risk report generated by AI / CRE workflow
    struct RiskReport {
        uint256 reportId;
        uint256 timestamp;
        uint256 riskLevel; // 0–100
        string summary;
    }

    /// @notice Emitted when a new risk report is submitted
    event RiskReportSubmitted(
        address indexed user,
        uint256 indexed reportId,
        uint256 riskLevel
    );

    /// @notice Submit a risk report for a user
    /// @param user The affected user
    /// @param riskLevel Risk score (0–100)
    function submitRiskReport(
        address user,
        uint256 riskLevel
    ) external;

    /// @notice Get the latest risk report for a user
    function getLatestReport(
        address user
    ) external view returns (RiskReport memory);
}
